# Programas reales de ESIC extraídos de esic.co y esic.edu
# Fuentes consultadas: https://esic.co/programas/ y https://www.esic.edu/

PROGRAMAS_ESIC = [
    {
        "id": "PROG-001",
        "nombre": "Dirección de Marketing Global",
        "area": "Marketing",
        "nivel": "Pregrado",
        "modalidad": "Presencial",
        "duracion": "4 años",
        "descripcion": "Doble titulación Colombia/España. Formación en marketing estratégico y gestión comercial global.",
        "requisitos": "Título de bachiller",
    },
    {
        "id": "PROG-002",
        "nombre": "Digital Business",
        "area": "Negocios Digitales",
        "nivel": "Pregrado",
        "modalidad": "Presencial",
        "duracion": "4 años",
        "descripcion": "Doble titulación. Preparación en negocios digitales, transformación digital y emprendimiento.",
        "requisitos": "Título de bachiller",
    },
    {
        "id": "PROG-003",
        "nombre": "Máster en Digital Marketing",
        "area": "Marketing Digital",
        "nivel": "Máster",
        "modalidad": "Híbrida",
        "duracion": "11 meses",
        "descripcion": "Acelera tu carrera con el Máster + Global Management Program en Digital Marketing de ESIC Medellín. Planeación estratégica digital, análisis de datos, SEO y redes sociales.",
        "requisitos": "Título profesional o experiencia equivalente",
    },
    {
        "id": "PROG-004",
        "nombre": "Máster en Customer Experience, Innovation & Design Thinking",
        "area": "Customer Experience",
        "nivel": "Máster",
        "modalidad": "Híbrida",
        "duracion": "11 meses",
        "descripcion": "GMP + Máster Customer Experience Management. Enfoque en experiencia del cliente, innovación y design thinking.",
        "requisitos": "Título profesional",
    },
    {
        "id": "PROG-005",
        "nombre": "Máster en Digital Business",
        "area": "Negocios Digitales",
        "nivel": "Máster",
        "modalidad": "Híbrida",
        "duracion": "11 meses",
        "descripcion": "Formación en negocios digitales, estrategia digital y gestión de proyectos digitales.",
        "requisitos": "Título profesional",
    },
    {
        "id": "PROG-006",
        "nombre": "Executive Program",
        "area": "Liderazgo",
        "nivel": "Programa Ejecutivo",
        "modalidad": "Presencial",
        "duracion": "4 meses",
        "descripcion": "Liderazgo y transformación digital para directivos.",
        "requisitos": "Experiencia directiva",
    },
    {
        "id": "PROG-007",
        "nombre": "Máster Universitario en Administración de Empresas (MBA)",
        "area": "MBA",
        "nivel": "Máster Universitario",
        "modalidad": "Full Time Presencial",
        "duracion": "Octubre 2026 - Julio 2027",
        "descripcion": "Máster Universitario en Administración de Empresas de ESIC University. Estrategia, marketing, operaciones, finanzas, analítica de datos, liderazgo e innovación.",
        "requisitos": "Título universitario y experiencia profesional",
    },
    {
        "id": "PROG-008",
        "nombre": "Executive MBA (EMBA)",
        "area": "MBA",
        "nivel": "Máster de Formación Permanente",
        "modalidad": "Presencial/Online",
        "duracion": "12 meses",
        "descripcion": "Preparación de directores de negocio. Enfoque en liderazgo, innovación y sostenibilidad.",
        "requisitos": "Experiencia directiva relevante",
    },
    {
        "id": "PROG-009",
        "nombre": "Máster en Dirección de Marketing y Gestión Comercial (GESCO)",
        "area": "Marketing y Ventas",
        "nivel": "Máster de Formación Permanente",
        "modalidad": "Presencial/Online",
        "duracion": "12 meses",
        "descripcion": "Visión estratégica, técnicas y herramientas para liderar marketing, gestión comercial y desarrollo de negocio.",
        "requisitos": "Título profesional",
    },
    {
        "id": "PROG-010",
        "nombre": "Máster en Finanzas (MDF)",
        "area": "Finanzas",
        "nivel": "Máster de Formación Permanente",
        "modalidad": "Presencial/Online",
        "duracion": "12 meses",
        "descripcion": "Preparación para asumir responsabilidades en la dirección financiera de la empresa.",
        "requisitos": "Título profesional o experiencia financiera",
    },
    {
        "id": "PROG-011",
        "nombre": "Máster en Marketing Digital (MMD)",
        "area": "Marketing Digital",
        "nivel": "Máster de Formación Permanente",
        "modalidad": "Presencial/Online",
        "duracion": "12 meses",
        "descripcion": "Gestión de proyectos digitales: posicionamiento, datos, redes sociales y e-commerce omnicanal.",
        "requisitos": "Título profesional",
    },
    {
        "id": "PROG-012",
        "nombre": "Postgrado en Marketing Digital (PSMD)",
        "area": "Marketing Digital",
        "nivel": "Postgrado",
        "modalidad": "Presencial",
        "duracion": "5 meses",
        "descripcion": "Comunicar productos y servicios con éxito a través de Internet en todo tipo de medios.",
        "requisitos": "Título profesional",
    },
    {
        "id": "PROG-013",
        "nombre": "Postgrado en Big Data & Business Analytics",
        "area": "Analítica de Datos",
        "nivel": "Postgrado",
        "modalidad": "Presencial/Online",
        "duracion": "4-6 meses",
        "descripcion": "Especialización en Big Data, analítica de negocio y toma de decisiones basada en datos.",
        "requisitos": "Título profesional",
    },
    {
        "id": "PROG-014",
        "nombre": "Postgrado en Dirección de Ventas (PSDV)",
        "area": "Ventas",
        "nivel": "Postgrado",
        "modalidad": "Presencial/Online",
        "duracion": "4-6 meses",
        "descripcion": "Programa con más de 190 ediciones. Formación en dirección comercial y gestión de ventas.",
        "requisitos": "Título profesional",
    },
    {
        "id": "PROG-015",
        "nombre": "Máster en International Business",
        "area": "Negocios Internacionales",
        "nivel": "Máster de Formación Permanente",
        "modalidad": "Presencial/Online",
        "duracion": "12 meses",
        "descripcion": "Formación en comercio internacional, estrategia global y gestión de operaciones multinacionales.",
        "requisitos": "Título profesional",
    },
]


def get_programas():
    return [dict(p, tipo="programa") for p in PROGRAMAS_ESIC]
